  name: Node.js CI

  on:
    push:
        branches: ["main"]
    pull_request: 
          branches: ["main", "dev"]

  jobs:
      build:
          name: Backend test
          runs-on: ubuntu-latest

          defaults:
              run:
                  working-directory: ./quirknotes/backend

          strategy:
              matrix:
                  node-version: [20.x]

          steps:
              - uses: actions/checkout@v3

              - name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                  node-version: ${{ matrix.node-version }}
              - name: Installing Mongodb
                run: |
                  sudo apt-get install gnupg curl
                  curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
                  echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
                  sudo apt-get update
                  sudo apt-get install -y mongodb-org
              - name: Starting Mongodb
                run: mongod --dbpath=./quirknotes/backend/data/db
              - run: npm i
              - run: npm test